create table Clienti2 (
	id INT,
	nome VARCHAR(50),
	citta VARCHAR(50)
);
insert into Clienti2 (id, nome, citta) values (1, 'Alleyn Aindriu', 'Guadalupe');
insert into Clienti2 (id, nome, citta) values (2, 'Kaiser Khristoforov', 'Lais');
insert into Clienti2 (id, nome, citta) values (3, 'Margaretta Giannassi', 'Bazar-Korgon');
insert into Clienti2 (id, nome, citta) values (4, 'Karil Bambrugh', 'Buzet');
insert into Clienti2 (id, nome, citta) values (5, 'Guglielma O''Hone', 'Komsomolsk');
insert into Clienti2 (id, nome, citta) values (6, 'Alison Duckit', 'Meixian');
insert into Clienti2 (id, nome, citta) values (7, 'Dennie Littefair', 'Ptení');
insert into Clienti2 (id, nome, citta) values (8, 'Joshia Okroy', 'Uryupinsk');
insert into Clienti2 (id, nome, citta) values (9, 'Leia Endricci', 'Sicheng');
insert into Clienti2 (id, nome, citta) values (10, 'Torey Bousquet', 'Ulset');
insert into Clienti2 (id, nome, citta) values (11, 'Francisca Boughton', 'Bordeaux');
insert into Clienti2 (id, nome, citta) values (12, 'Hayes Beeck', 'Buawan');
insert into Clienti2 (id, nome, citta) values (13, 'Ivory Klagges', 'Binucayan');
insert into Clienti2 (id, nome, citta) values (14, 'Roy Chessman', 'Gemblengmulyo');
insert into Clienti2 (id, nome, citta) values (15, 'Dorelle Gumby', 'Malaga');
insert into Clienti2 (id, nome, citta) values (16, 'Dorthea Pennoni', 'Paris 09');
insert into Clienti2 (id, nome, citta) values (17, 'Roarke Rosel', 'Shorapani');
insert into Clienti2 (id, nome, citta) values (18, 'Gregg Badsey', 'Taiping');
insert into Clienti2 (id, nome, citta) values (19, 'Eal Grimolbie', 'Gines-Patay');
insert into Clienti2 (id, nome, citta) values (20, 'Kate Sallowaye', 'Apitong');
insert into Clienti2 (id, nome, citta) values (21, 'Aleen Ferrelli', 'Asopós');
insert into Clienti2 (id, nome, citta) values (22, 'Culley Gabey', 'Hengjie');
insert into Clienti2 (id, nome, citta) values (23, 'Lyndsie Latek', 'Lechinkay');
insert into Clienti2 (id, nome, citta) values (24, 'Davon Conwell', 'Timrå');
insert into Clienti2 (id, nome, citta) values (25, 'Maren Elphinston', 'Flagstaff');
insert into Clienti2 (id, nome, citta) values (26, 'Hollie Heald', 'Olival Basto');
insert into Clienti2 (id, nome, citta) values (27, 'Patsy Marcq', 'Hengshui');
insert into Clienti2 (id, nome, citta) values (28, 'Stefania Gilhooley', 'Komsomolets');
insert into Clienti2 (id, nome, citta) values (29, 'Marisa Masurel', 'Borzęta');
insert into Clienti2 (id, nome, citta) values (30, 'Elenore Zute', 'Doumen');
insert into Clienti2 (id, nome, citta) values (31, 'Dexter Shavel', 'Jinji');
insert into Clienti2 (id, nome, citta) values (32, 'Arnuad Legg', 'Were');
insert into Clienti2 (id, nome, citta) values (33, 'Jessy Kobke', 'Brloh');
insert into Clienti2 (id, nome, citta) values (34, 'Corina McCart', 'Coromandel');
insert into Clienti2 (id, nome, citta) values (35, 'Gearalt Forstall', 'Maripa');
insert into Clienti2 (id, nome, citta) values (36, 'Barnabe Jerosch', '‘Anātā');
insert into Clienti2 (id, nome, citta) values (37, 'Carrol Carmody', 'Tianjiaba');
insert into Clienti2 (id, nome, citta) values (38, 'Daren Bills', 'Ordóñez');
insert into Clienti2 (id, nome, citta) values (39, 'Berthe Dymond', 'Kharagauli');
insert into Clienti2 (id, nome, citta) values (40, 'Dyann McCart', 'Shāhīn Dezh');
insert into Clienti2 (id, nome, citta) values (41, 'Wheeler MacCracken', 'Sukowiryo');
insert into Clienti2 (id, nome, citta) values (42, 'Kriste Elstow', 'Vista Hermosa');
insert into Clienti2 (id, nome, citta) values (43, 'Bethina Milroy', 'Verkhniy Mamon');
insert into Clienti2 (id, nome, citta) values (44, 'Salli Sandom', 'Marinići');
insert into Clienti2 (id, nome, citta) values (45, 'Reynold Enden', 'Payao');
insert into Clienti2 (id, nome, citta) values (46, 'Rooney Woodroofe', 'Ruše');
insert into Clienti2 (id, nome, citta) values (47, 'Marietta Rochford', 'Rueil-Malmaison');
insert into Clienti2 (id, nome, citta) values (48, 'Elisabetta Bratch', 'Tsagaan-Ovoo');
insert into Clienti2 (id, nome, citta) values (49, 'Catlaina Layman', 'Jaša Tomić');
insert into Clienti2 (id, nome, citta) values (50, 'Charmain Busk', 'Nanshe');
insert into Clienti2 (id, nome, citta) values (51, 'Artair McClenan', 'Yanfolila');
insert into Clienti2 (id, nome, citta) values (52, 'Jayne Vanne', 'Veyno');
insert into Clienti2 (id, nome, citta) values (53, 'Andriana Thorington', 'Ciwidara');
insert into Clienti2 (id, nome, citta) values (54, 'Maggie Ventom', 'Fundación');
insert into Clienti2 (id, nome, citta) values (55, 'Devonna Rodden', 'Dacudao');
insert into Clienti2 (id, nome, citta) values (56, 'Lizabeth Lipson', 'Rukaj');
insert into Clienti2 (id, nome, citta) values (57, 'Bond Ridgers', 'Lianyi');
insert into Clienti2 (id, nome, citta) values (58, 'Neda Jaffrey', 'Barili');
insert into Clienti2 (id, nome, citta) values (59, 'Lanita Barthorpe', 'Pilpichaca');
insert into Clienti2 (id, nome, citta) values (60, 'Frannie Bartos', 'Colomi');
insert into Clienti2 (id, nome, citta) values (61, 'Aubrey MacConneely', 'Gegernoong');
insert into Clienti2 (id, nome, citta) values (62, 'Lorita Langrish', 'Borek Wielkopolski');
insert into Clienti2 (id, nome, citta) values (63, 'Gan Bengefield', 'Okigwi');
insert into Clienti2 (id, nome, citta) values (64, 'Sax Ashbrook', 'Ampera');
insert into Clienti2 (id, nome, citta) values (65, 'Clovis Lisle', 'Kista');
insert into Clienti2 (id, nome, citta) values (66, 'Dilly Layman', 'Aygepat');
insert into Clienti2 (id, nome, citta) values (67, 'Dredi Gammage', 'Córdoba');
insert into Clienti2 (id, nome, citta) values (68, 'Alfy Bisset', 'Muang Phôn-Hông');
insert into Clienti2 (id, nome, citta) values (69, 'Emelda Glasebrook', 'Standerton');
insert into Clienti2 (id, nome, citta) values (70, 'Hew De Blasiis', 'Kupusina');
insert into Clienti2 (id, nome, citta) values (71, 'Hamilton Fishburn', 'Candelária');
insert into Clienti2 (id, nome, citta) values (72, 'Carola Bottomer', 'Cabouco');
insert into Clienti2 (id, nome, citta) values (73, 'Ardella Corbould', 'Ādīs Zemen');
insert into Clienti2 (id, nome, citta) values (74, 'Sadye Croucher', 'Sohag');
insert into Clienti2 (id, nome, citta) values (75, 'Shadow Dericot', 'Täby');
insert into Clienti2 (id, nome, citta) values (76, 'Tades Gladdish', 'Loga');
insert into Clienti2 (id, nome, citta) values (77, 'Reilly Gunda', 'Bualu');
insert into Clienti2 (id, nome, citta) values (78, 'Vanya Luc', 'Aveiro');
insert into Clienti2 (id, nome, citta) values (79, 'Launce Dudden', 'Colcabamba');
insert into Clienti2 (id, nome, citta) values (80, 'Marina Gorrie', 'Xishan');
insert into Clienti2 (id, nome, citta) values (81, 'Seth Mixhel', 'Kamiichi');
insert into Clienti2 (id, nome, citta) values (82, 'Rosalyn Huckerbe', 'La Huerta');
insert into Clienti2 (id, nome, citta) values (83, 'Thedric Grimsdike', 'Dongmafang');
insert into Clienti2 (id, nome, citta) values (84, 'Vern Banks', 'Paris 19');
insert into Clienti2 (id, nome, citta) values (85, 'Stephan Coggen', 'Jiesheng');
insert into Clienti2 (id, nome, citta) values (86, 'Pall Innocent', 'Kävlinge');
insert into Clienti2 (id, nome, citta) values (87, 'Maud Adanet', 'Lidingö');
insert into Clienti2 (id, nome, citta) values (88, 'Jordana Druitt', 'Grimshaw');
insert into Clienti2 (id, nome, citta) values (89, 'Ingar Borborough', 'Kalatongke');
insert into Clienti2 (id, nome, citta) values (90, 'Pearle McGready', 'Reuleuet');
insert into Clienti2 (id, nome, citta) values (91, 'Magdaia Gorden', 'Muricay');
insert into Clienti2 (id, nome, citta) values (92, 'Ryley Poolton', 'Guinoaliuan');
insert into Clienti2 (id, nome, citta) values (93, 'Jody Casbourne', 'Ujar');
insert into Clienti2 (id, nome, citta) values (94, 'Vera Londesborough', 'Lugo');
insert into Clienti2 (id, nome, citta) values (95, 'Rosette Lazer', 'Göteborg');
insert into Clienti2 (id, nome, citta) values (96, 'Annamarie Dummett', 'Reina Mercedes');
insert into Clienti2 (id, nome, citta) values (97, 'Beale Alloway', 'Kildare');
insert into Clienti2 (id, nome, citta) values (98, 'Yalonda Yeomans', 'Elimäki');
insert into Clienti2 (id, nome, citta) values (99, 'Marcia Maddocks', 'Roanoke');
insert into Clienti2 (id, nome, citta) values (100, 'Wilfrid Perocci', 'Mtubatuba');