CREATE DATABASE esercizio1;

USE esercizio1;

create table Libri (
	id INT,
	titolo VARCHAR(511),
	autore VARCHAR(50),
	genere VARCHAR(50),
	anno_pubblicazione INT,
	prezzo DECIMAL(6,2)
);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (1, 'Yossi (Ha-Sippur Shel Yossi)', 'Millicent Jeaves', 'Drama|Romance', 1999, 965.44);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (2, 'Mask of Zorro, The', 'Romain Bulbeck', 'Action|Comedy|Romance', 2012, 90.67);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (3, 'Beyond the Valley of the Dolls', 'Samuel Pargeter', 'Comedy|Horror', 2015, 301.45);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (4, 'Petulia', 'Bennie Arnot', 'Drama', 2009, 528.82);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (5, 'Extraordinary Adventures of Mr. West in the Land of the Bolsheviks, The (Neobychainye priklyucheniya mistera Vesta v strane bolshevikov)', 'Adella Rosi', 'Comedy', 2002, 926.32);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (6, 'Safety Last!', 'Arvin Backwell', 'Action|Comedy|Romance', 2009, 894.89);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (7, 'Charley Varrick', 'Cass McCray', 'Crime|Drama|Thriller', 2016, 622.12);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (8, 'Dragon Ball Z: Dead Zone (Doragon bôru Z 1: Ora no Gohan wo kaese)', 'Nevsa Gowar', 'Action|Adventure|Animation|Fantasy|Sci-Fi', 2016, 774.13);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (9, 'Virgin Suicides, The', 'Winnie Crichten', 'Drama|Romance', 1990, 379.87);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (10, 'Town That Dreaded Sundown, The', 'Tamra Verson', 'Crime|Drama|Horror|Mystery|Thriller', 2015, 915.56);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (11, 'Harry Brown', 'Atalanta Oddy', 'Crime|Drama|Thriller', 2017, 858.37);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (12, 'Every Night Dreams (Each Night I Dream) (Yogoto no yume)', 'Katie Wolledge', 'Drama', 2024, 896.55);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (13, 'Larks on a String (Skrivánci na niti)', 'Nissa Souley', 'Comedy|Drama|Romance', 2020, 503.83);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (14, 'Calle 54', 'Lulu Brangan', 'Documentary|Musical', 2019, 577.28);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (15, 'Beat That My Heart Skipped, The (battre mon coeur s''est arrêté, De)', 'Davis Gatrill', 'Drama', 2010, 180.59);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (16, 'In A Day', 'Natalee Giorgiutti', 'Romance', 2007, 170.23);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (17, 'Summer Days With Coo', 'Kimbra Suett', 'Animation', 2026, 798.84);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (18, 'Lemon Tree', 'Dirk Ailsbury', 'Drama', 1992, 417.05);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (19, 'FBI: Frikis buscan incordiar', 'Armin Morffew', '(no genres listed)', 2017, 838.74);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (20, 'Wildflowers', 'Jackquelin Grute', 'Drama', 2024, 644.26);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (21, 'Fear and Trembling (Stupeur et tremblements)', 'Katrina Edgler', 'Comedy', 2009, 322.78);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (22, 'Transit', 'Sybil Caffin', 'Crime|Drama|Thriller', 1991, 79.46);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (23, 'Sanatorium', 'Marthe Buttrum', 'Thriller', 2014, 639.26);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (24, 'Way... Way Out', 'Tristam Bransby', 'Comedy|Sci-Fi', 2021, 393.72);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (25, 'Moonbase', 'Frayda Vedikhov', 'Sci-Fi', 2025, 690.77);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (26, 'Heavenly Forest', 'Caro Swafield', 'Drama|Romance', 2017, 82.31);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (27, 'Comes a Horseman', 'Wally Loisi', 'Drama|Romance|Western', 1994, 700.84);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (28, 'Ricky Gervais Live 4: Science', 'Hewitt Koppel', 'Comedy', 1993, 456.17);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (29, 'When Worlds Collide', 'Codie Medling', 'Sci-Fi', 1997, 492.12);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (30, 'Fetishes', 'Leelah Coverdill', 'Documentary', 2019, 120.91);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (31, 'Curb Dance', 'Christiano Gaggen', '(no genres listed)', 2011, 17.23);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (32, 'Man with the Golden Gun, The', 'Danielle Prout', 'Action|Adventure|Thriller', 2015, 968.69);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (33, 'Soup to Nuts', 'Philomena Lamming', 'Comedy|Romance', 1998, 689.74);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (34, 'Alice (Neco z Alenky)', 'Carmella Brugmann', 'Animation|Fantasy|Mystery', 2001, 834.83);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (35, 'Dinner Rush', 'Laural Mikalski', 'Drama', 2026, 964.71);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (36, 'R100', 'Nat Mesias', 'Comedy|Drama', 1995, 89.06);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (37, 'Boys Town', 'Tanny Streader', 'Drama', 2008, 577.94);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (38, 'Burning, The', 'Sebastian Wiggins', 'Horror', 2005, 519.26);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (39, 'Wind That Shakes the Barley, The', 'Scotty Lodford', 'Drama|War', 2024, 714.36);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (40, 'Favela Rising', 'Roderich Soar', 'Documentary', 1992, 986.47);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (41, 'Life Less Ordinary, A', 'Al Dallman', 'Romance|Thriller', 2000, 462.64);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (42, 'If I Had a Million', 'Charline Ledbetter', 'Comedy|Drama', 2002, 169.07);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (43, 'Goats', 'Roth Shand', 'Comedy', 2005, 171.21);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (44, 'Sunset Limited, The', 'Louie Kharchinski', 'Drama', 1992, 939.49);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (45, 'Slender Thread, The', 'Enid Pratty', 'Drama', 2011, 181.52);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (46, 'Into the Storm', 'Jess Elcoux', 'Action|Thriller', 1992, 958.91);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (47, 'Dancemaker', 'Jasmine Krzysztofiak', 'Documentary', 1999, 38.54);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (48, 'Chasing Christmas', 'Peirce Poltun', 'Comedy|Fantasy', 1995, 162.81);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (49, 'Atomic Cafe, The', 'Simona Eshelby', 'Documentary|War', 2023, 294.38);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (50, 'Playing with Love (Puppy Love) (Maladolescenza)', 'Kingston Fishleigh', 'Drama', 2003, 347.24);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (51, 'Way Home, The (Jibeuro)', 'Abel Praton', 'Drama', 2017, 849.09);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (52, 'Igby Goes Down', 'Ninon MacVay', 'Comedy|Drama', 2017, 886.33);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (53, 'The Trans-Atlantic Mystery', 'Justinn But', '(no genres listed)', 2023, 28.81);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (54, 'Unsaid, The', 'Elyn Clavering', 'Crime|Drama|Mystery', 2014, 360.48);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (55, 'Cobra', 'Helene Farland', 'Action|Crime', 2018, 601.33);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (56, 'Ticket To Romance (En enkelt til Korsør)', 'Jonas Tainton', 'Comedy|Drama|Romance', 2003, 328.8);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (57, 'Let Fury Have the Hour', 'Joyous Levesque', 'Documentary', 2014, 263.89);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (58, 'Cyrano de Bergerac', 'Lionello Belsher', 'Comedy|Drama|Romance', 2014, 328.23);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (59, 'Sputnik', 'Trude Drakers', '(no genres listed)', 2014, 25.62);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (60, 'Rebel Without a Cause', 'Dennison Nicklen', 'Drama', 2008, 830.38);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (61, 'Glue', 'Tracie Garrould', 'Drama', 2017, 974.35);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (62, 'Power of Kangwon Province, The (Kangwon-do ui him)', 'Thayne Benting', 'Drama', 2019, 919.11);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (63, 'Shanghai Kiss', 'Devland Etheridge', 'Comedy|Drama|Romance', 1999, 793.72);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (64, 'Puss in Boots: The Three Diablos', 'Tamiko Gully', 'Animation|Comedy', 2023, 517.42);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (65, 'Princess', 'Helge Schruur', 'Action|Animation|Drama', 2024, 350.48);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (66, '100 Ways to Murder Your Wife (Sha qi er ren zu)', 'Dido Dulanty', 'Comedy', 2024, 534.14);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (67, 'Escapist, The', 'Jeri Frensche', 'Thriller', 2002, 211.51);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (68, 'Castaway', 'Arnie Poad', 'Adventure|Drama', 1997, 761.74);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (69, 'Wing and a Prayer', 'Pauly Arunowicz', 'Action|Drama|War', 1995, 660.08);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (70, 'Lucky Lady', 'Letti Wanless', 'Comedy|Drama', 2010, 303.0);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (71, 'America''s Heart and Soul', 'Eziechiele Schubbert', 'Documentary', 2000, 314.62);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (72, 'Romantic Comedy', 'Georgette Duplan', 'Comedy', 2024, 426.79);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (73, 'End of the Line, The', 'Addie Jeggo', 'Documentary', 2016, 433.89);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (74, '8 1/2 (8½)', 'Tana McGall', 'Drama|Fantasy', 2020, 603.21);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (75, 'Born Reckless', 'Kalila Tredgold', 'Action|Adventure|Crime|Drama|Romance', 2025, 260.3);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (76, 'At Long Last Love', 'Aretha Tarbin', 'Comedy|Musical|Romance', 2021, 228.3);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (77, 'Samoure', 'Idalina Kasparski', 'Drama', 2024, 464.25);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (78, 'House II: The Second Story', 'Barbara Chastenet', 'Comedy|Fantasy|Horror', 2010, 752.74);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (79, 'Lines: Horizontal', 'Kamillah Arnholtz', 'Animation', 2012, 819.74);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (80, 'Steel Dawn', 'Alisun Derkes', 'Action|Sci-Fi', 2017, 176.78);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (81, 'Horse in the Gray Flannel Suit, The', 'Bram Serotsky', 'Children|Comedy', 1990, 165.45);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (82, 'It''s a Very Merry Muppet Christmas Movie', 'Danni Bathow', 'Children|Comedy', 1991, 283.18);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (83, 'Mrs. Henderson Presents', 'Paton Hinkins', 'Comedy|Drama', 2013, 954.26);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (84, 'Entitled, The', 'Joni Heyns', 'Thriller', 2012, 128.55);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (85, 'Smurfs 2, The', 'Maurine Packe', 'Animation|Children|Comedy', 2013, 512.85);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (86, 'Violette', 'Corissa Martinie', 'Drama', 2008, 743.65);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (87, 'Equinox Flower (Higanbana)', 'Cody Banfill', 'Comedy|Drama', 2007, 238.26);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (88, 'Black Dynamite', 'Katha Gilbard', 'Action|Comedy', 1996, 573.97);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (89, 'No Mercy (Yongseoneun Eupda)', 'Arlen Lardeur', 'Thriller', 1999, 920.27);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (90, 'Death Hunt', 'Nobie Gillespie', 'Action|Adventure|Crime|Thriller', 2008, 836.36);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (91, 'Rudy', 'Cece Pope', 'Drama', 2007, 543.83);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (92, 'Nude Bomb, The', 'Whit Gibbon', 'Comedy', 2014, 706.04);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (93, 'Krakatoa, East of Java', 'Mannie Espinet', 'Adventure|Drama', 2010, 245.66);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (94, 'Silentium', 'Katherina Bum', 'Crime|Thriller', 1990, 305.96);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (95, 'Mad Love', 'Rhodie Thurling', 'Drama|Romance', 2012, 711.76);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (96, 'Interiors', 'Katy Arro', 'Drama', 1999, 604.6);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (97, 'Turning, The', 'Anthia Cakes', 'Drama', 2024, 143.73);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (98, 'Choking Man', 'Francoise Jansey', 'Drama', 2000, 168.59);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (99, 'A Night at the Movies: The Suspenseful World of Thrillers', 'Aarika Lemary', 'Documentary', 2026, 949.26);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (100, 'Billy Bathgate', 'Ward Diddams', 'Crime|Drama', 2019, 95.13);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (101, 'Solo Sunny', 'Christen Galley', 'Drama|Musical|Romance', 2004, 106.84);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (102, 'Great Silence, The (Grande silenzio, Il)', 'Agnella Laden', 'Drama|Western', 1998, 625.71);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (103, 'Dangerous Place, A', 'Howey Beetles', 'Thriller', 2009, 846.5);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (104, 'March of the Movies (Film Parade, The)', 'Rusty Bothbie', 'Documentary', 2001, 812.25);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (105, 'Serious Man, A', 'Kaela Creswell', 'Comedy|Drama', 2007, 143.97);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (106, 'Seventh Cross, The', 'Carlina Vieyra', 'Drama|War', 2015, 928.74);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (107, 'Eye, The', 'Hermina Gras', 'Drama|Horror|Thriller', 1997, 26.2);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (108, 'Superman/Batman: Public Enemies', 'Lou Sedge', 'Action|Animation|Fantasy', 2021, 683.59);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (109, 'Murphy''s Law', 'Hakim Briston', 'Action', 2021, 901.85);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (110, 'Interkosmos', 'Syd MacEvilly', 'Drama', 2012, 562.63);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (111, 'When Worlds Collide', 'Rozele Trevers', 'Sci-Fi', 1994, 388.43);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (112, 'Eve and the Fire Horse', 'Carolina Mea', 'Drama', 2018, 491.2);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (113, 'Lovely, Still', 'Adelice Taffley', 'Drama|Romance', 1991, 17.06);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (114, 'Night Walker, The', 'Adara Phlipon', 'Horror|Mystery|Thriller', 1991, 183.89);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (115, 'Russell Peters: The Green Card Tour - Live from the O2 Arena', 'Jessalin Venditto', 'Comedy|Documentary', 2008, 999.22);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (116, 'Chocolate Soldier, The', 'Gerhard Clyde', 'Comedy|Musical', 1991, 190.93);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (117, 'Blended', 'Phineas Ecles', 'Comedy', 1995, 634.31);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (118, 'Killer Elite', 'Zeb Gotfrey', 'Action|Thriller', 1991, 516.79);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (119, 'You Can''t Take It with You', 'Dona Neilly', 'Comedy|Romance', 2023, 482.81);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (120, 'Adventures of Mary-Kate and Ashley, The: The Case of the United States Navy Adventure', 'Jami Cleaves', 'Children|Musical|Mystery', 2008, 150.47);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (121, 'Afghan Star', 'Olwen Oller', 'Documentary', 2018, 610.9);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (122, 'Mood Indigo (L''écume des jours)', 'Ellery Devereu', 'Drama|Fantasy', 1992, 611.82);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (123, 'The Facts of Murder', 'Nadya Cassius', 'Crime|Drama', 2001, 551.91);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (124, 'Barnacle Bill', 'Stefanie Rymell', 'Comedy|Drama', 2011, 784.97);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (125, 'Fade to Black', 'Darcey Cannicott', 'Documentary', 1995, 762.76);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (126, 'Pet Sematary', 'Andra Augar', 'Horror', 2004, 250.49);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (127, 'V.I.P.s, The', 'Alister Lloyd', 'Drama', 2015, 370.5);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (128, 'Snowtown (Snowtown Murders, The)', 'Friedrich Kumar', 'Crime|Drama|Thriller', 2010, 293.92);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (129, 'Julien Donkey-Boy', 'Joanne Pendre', 'Drama', 2005, 236.77);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (130, 'Dancer Upstairs, The', 'Olive O''Spillane', 'Crime|Drama|Thriller', 2019, 671.43);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (131, 'Escobar: Paradise Lost', 'Farah Dimic', 'Romance|Thriller', 2006, 25.89);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (132, 'Tenth Man, The', 'Denyse Durtnell', 'Drama|War', 1992, 446.81);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (133, 'Dark Days', 'Micah Fulstow', 'Documentary', 2026, 154.03);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (134, 'Article 99', 'Chiquia Sultan', 'Comedy|Drama', 1997, 982.82);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (135, 'Wrath of God, The', 'Ansley Blaiklock', 'Western', 1995, 884.66);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (136, 'Tank Girl', 'Dorolisa Darby', 'Action|Comedy|Sci-Fi', 1995, 449.87);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (137, 'For a Good Time, Call...', 'Herculie Havock', 'Comedy|Drama|Romance', 2014, 262.82);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (138, 'French Fried Vacation (Les Bronzés)', 'Marti de Courcey', 'Comedy', 2022, 931.55);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (139, 'Eternity and a Day (Mia aoniotita kai mia mera)', 'Demetria Aitken', 'Drama', 2026, 304.36);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (140, 'Brokedown Palace', 'Laura Benedict', 'Drama', 2002, 295.19);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (141, '13th Letter, The', 'Creighton Reeken', 'Film-Noir', 1998, 873.2);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (142, 'Trust the Man', 'Pebrook Kenningley', 'Comedy|Drama|Romance', 2014, 52.48);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (143, 'Triggermen', 'Goldy Odeson', 'Comedy|Crime', 2015, 775.4);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (144, 'The Horribly Slow Murderer with the Extremely Inefficient Weapon', 'Anatole Bohey', 'Comedy|Horror', 2021, 620.64);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (145, 'King of Fighters, The', 'Mort Gowanson', 'Action|Sci-Fi', 2005, 387.35);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (146, 'Pervert''s Guide to Cinema, The', 'Dolli Greenhaugh', 'Documentary', 2016, 295.18);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (147, 'Repulsion', 'Harrie Stapford', 'Drama|Horror', 2008, 462.23);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (148, 'Enough', 'Aloise Descroix', 'Drama|Thriller', 1993, 950.6);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (149, 'Young Detective Dee: Rise of the Sea Dragon (Di Renjie: Shen du long wang)', 'Shirlene Dewitt', 'Action|Adventure|Drama|Fantasy|Mystery|IMAX', 2010, 569.77);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (150, 'B*A*P*S', 'Luther McGeagh', 'Comedy', 1990, 283.83);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (151, 'Dictator, The', 'Charmaine Maylin', 'Comedy', 1994, 172.14);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (152, 'Wog Boy, The', 'Leland Latore', 'Comedy', 2003, 269.87);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (153, 'Tale of Cinema (Geuk jang jeon)', 'Fleurette Cowwell', 'Drama', 2017, 982.45);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (154, 'Leprechaun 4: In Space', 'Zachary Sherborne', 'Comedy|Fantasy|Horror|Sci-Fi', 2006, 330.77);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (155, 'Louie Bluie', 'Martainn Ciubutaro', 'Documentary', 2006, 212.26);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (156, 'Julia', 'Felike Archbald', 'Drama', 2003, 165.78);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (157, 'Stolen (Stolen Lives)', 'Jard Schurig', 'Crime|Drama|Mystery|Thriller', 2023, 506.21);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (158, 'Leningrad Cowboys Meet Moses', 'Wilton Bonde', 'Adventure|Comedy', 2018, 333.81);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (159, 'Miami Blues', 'Cirillo Gehring', 'Comedy|Crime|Drama', 2000, 193.83);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (160, 'Dangerous Liaisons', 'Ogdan Churchley', 'Drama|Romance', 2003, 187.02);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (161, 'Deliverance', 'Sada Filipov', 'Adventure|Drama|Thriller', 2015, 293.61);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (162, 'Swimsuit Issue, The (Allt flyter)', 'Audi Nazaret', 'Comedy|Drama', 2020, 392.0);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (163, 'War Witch (Rebelle)', 'Cass Medlin', 'Drama|War', 2018, 790.05);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (164, 'Beauty of the Day (Belle de jour)', 'Tammara Vasyanin', 'Drama', 1992, 274.29);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (165, 'The Boy Next Door', 'Clarance Spinello', 'Thriller', 1991, 264.15);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (166, 'Lady and the Tramp', 'Bryon Ruecastle', 'Animation|Children|Comedy|Romance', 2014, 899.39);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (167, 'Balls Out: Gary the Tennis Coach', 'Velma Bundey', 'Comedy', 1995, 72.5);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (168, 'The Pool Boys', 'Magdalena Das', 'Comedy', 2018, 65.13);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (169, 'Space Is The Place', 'Zarah Macbeth', 'Sci-Fi', 1991, 733.79);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (170, 'Terrorist, The (a.k.a. Malli) (Theeviravaathi)', 'Edith Ashfold', 'Drama', 2011, 44.18);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (171, 'Underworld', 'Abramo Creavan', 'Action|Fantasy|Horror', 2007, 514.74);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (172, 'Wirey Spindell', 'Tallie Hitchens', 'Comedy', 2019, 614.64);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (173, 'Seven Invisible Men (Septyni nematomi zmones)', 'Stearn De Matteis', 'Drama', 2013, 136.37);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (174, 'Good Men, Good Women (Hao nan hao nu)', 'Murvyn Killner', 'Drama|Romance', 2017, 592.95);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (175, 'American Yakuza', 'Lucius Neubigging', 'Action|Drama|Thriller', 1994, 449.51);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (176, 'The Great Kidnapping', 'Carline Wimlet', 'Action|Crime|Thriller', 1998, 565.53);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (177, 'Alice Doesn''t Live Here Anymore', 'Victoria Ponder', 'Drama|Romance', 2003, 183.83);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (178, 'Bloody Murder 2: Closing Camp', 'Winna Hadwick', 'Drama|Horror|Mystery|Thriller', 1993, 313.88);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (179, 'Moonlight Murder', 'Briny Baal', 'Mystery', 2018, 730.39);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (180, 'Down by Law', 'Gisella Laborda', 'Comedy|Drama|Film-Noir', 2018, 570.42);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (181, 'Home Movie', 'Morgen Libermore', 'Documentary', 2015, 90.03);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (182, 'Aziz Ansari: Dangerously Delicious', 'Andreas Hinckesman', 'Comedy', 2026, 213.69);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (183, 'Big Shot''s Funeral (Da Wan)', 'Athene Ekell', 'Comedy', 2006, 311.25);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (184, 'Branded', 'Elsworth Dallicoat', 'Action|Drama|Mystery|Sci-Fi', 2008, 767.03);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (185, 'Anatomy of a Love Seen', 'Randi Halleybone', 'Drama|Romance', 1998, 873.03);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (186, 'Dark Water', 'Taryn Royse', 'Drama|Horror|Thriller', 2022, 326.31);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (187, 'Blood Done Sign My Name', 'Melisandra Roome', 'Drama', 1998, 913.16);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (188, 'Restless Souls (Bag det stille ydre)', 'Ameline Sly', 'Drama|Horror|Mystery', 2010, 906.03);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (189, 'Thorn Birds, The', 'Kylen Marchington', 'Drama|Romance', 1991, 445.3);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (190, 'Big Stampede, The', 'Athena Skoate', 'Western', 2004, 789.31);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (191, 'Drum', 'Jaymie Rusbridge', 'Thriller', 2001, 293.19);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (192, 'Cows (Vacas)', 'Donnie Rheaume', 'Drama', 2009, 467.84);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (193, 'Capricious Summer (Rozmarné léto)', 'Berny Kittel', 'Comedy', 1995, 51.97);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (194, 'I Accuse', 'Marna Fawdrey', 'Drama|Horror|War', 1998, 747.81);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (195, 'Oath, The', 'Ulises Sjostrom', 'Documentary', 1998, 445.76);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (196, 'Hello Herman', 'Ulrika Moreing', 'Drama', 2007, 473.0);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (197, 'In Name Only', 'Dix Riddlesden', 'Drama|Romance', 2023, 596.82);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (198, 'Battle of China, The (Why We Fight, 6)', 'Amelie Curror', 'Documentary|War', 2002, 763.7);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (199, 'Germany Pale Mother', 'Datha Traves', 'Drama|War', 2016, 867.59);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (200, 'Crimson Wing: Mystery of the Flamingos, The', 'Eward Marlin', 'Documentary', 2021, 417.68);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (201, 'Madonna''s Pig', 'Blinnie Briztman', 'Fantasy|Romance|Sci-Fi', 2011, 991.99);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (202, 'In the Shadow of the Moon', 'Krispin Duplan', 'Documentary', 2007, 80.08);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (203, 'Skins', 'Barr Auger', 'Crime|Drama', 2005, 325.81);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (204, 'Angriest Man in Brooklyn, The', 'Harley Kime', 'Comedy|Drama', 2025, 831.9);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (205, 'It', 'Corny Spriggen', 'Comedy|Romance', 2024, 66.51);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (206, 'I Met Him in Paris', 'Laurena Danzig', 'Comedy|Romance', 1994, 369.34);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (207, 'Not Here to Be Loved (Je ne suis pas là pour être aimé)', 'Wendi Grahlmans', 'Drama|Romance', 2006, 721.18);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (208, 'Cursed', 'Sondra Chate', 'Horror|Thriller', 2026, 811.16);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (209, 'Zodiac', 'Keelby Isbell', 'Sci-Fi', 1993, 81.18);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (210, 'Claustrofobia', 'Lisha Roloff', 'Thriller', 1997, 213.35);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (211, 'Murk (Mørke)', 'Heida Spinello', 'Drama|Thriller', 2002, 647.13);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (212, 'Tango & Cash', 'Sonnnie Dobing', 'Action|Comedy|Crime|Thriller', 2013, 416.35);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (213, 'Welcome to Mooseport', 'Annie Biaggelli', 'Comedy', 1994, 563.88);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (214, 'Red Hill', 'Shena D''Ambrosi', 'Crime|Thriller|Western', 1990, 700.99);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (215, 'Jonestown: Paradise Lost', 'Fionna Boylund', 'Documentary', 2026, 443.13);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (216, 'Against All Flags', 'Maurizia Groome', 'Action|Adventure|Drama|Romance', 2014, 556.32);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (217, 'Beware the Moon: Remembering ''An American Werewolf in London''', 'Carrissa Wiggett', 'Documentary', 2022, 702.81);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (218, 'Cook the Thief His Wife & Her Lover, The', 'Kelsey Powys', 'Comedy|Drama', 2021, 859.82);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (219, 'Bonnie and Clyde', 'Felipa Ovitts', 'Crime|Drama', 1998, 652.68);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (220, 'Buffet froid', 'Gauthier Weall', 'Comedy|Crime', 1993, 719.98);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (221, 'Poltergeist', 'Carlynne Wickliffe', 'Horror|Thriller', 2015, 270.9);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (222, 'When Evening Falls on Bucharest or Metabolism', 'Roanne Vales', '(no genres listed)', 2002, 768.02);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (223, 'Knute Rockne All American', 'Lindsey Eddowis', 'Drama', 2008, 816.49);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (224, 'Church, The (Chiesa, La)', 'Berti Kewish', 'Drama|Fantasy|Horror', 2024, 807.91);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (225, 'Prince of Pennsylvania, The', 'Jacky Semorad', 'Comedy|Drama', 2023, 765.43);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (226, 'Pear Tree, The (Derakhte Golabi)', 'Onfroi Landre', 'Drama|Romance', 2002, 169.9);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (227, 'Blackball', 'Sheelagh Logesdale', 'Comedy|Drama', 2022, 287.38);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (228, 'President''s Man, The', 'Magdalen Kasting', 'Action|Adventure|Thriller', 1995, 807.52);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (229, 'Fjols til fjells', 'Guntar Ibbeson', 'Comedy', 1992, 673.17);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (230, 'Cosmonaut, The', 'Annetta Mourant', 'Drama|Sci-Fi', 2022, 323.78);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (231, 'God Bless Ozzy Osbourne', 'Gussy McDonnell', 'Documentary', 2009, 546.53);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (232, 'Charlie Chan''s Courage', 'Kelley McHenry', 'Mystery', 1994, 72.55);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (233, 'Things You Can Tell Just by Looking at Her', 'Dorian Denkel', 'Drama|Romance', 1995, 210.11);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (234, 'Delicate Balance, A', 'Enoch Ramelot', 'Drama', 1996, 484.69);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (235, 'Land of Happines (Onnen maa)', 'Garek O''Dare', 'Drama', 2009, 365.32);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (236, 'Death Kiss, The', 'Tome MacPharlain', 'Comedy|Mystery', 2026, 383.71);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (237, 'Belle Starr', 'Alfie Poulgreen', 'Western', 2022, 636.47);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (238, 'Wisegirls', 'Cassondra Tizard', 'Crime|Drama', 2006, 275.75);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (239, 'I Wanna Hold Your Hand', 'Morgen Begent', 'Comedy', 1991, 544.35);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (240, 'Lenny', 'Webster Febre', 'Drama', 2009, 531.36);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (241, 'Mina Tannenbaum', 'Stanton Egentan', 'Drama', 1990, 166.09);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (242, 'Playground', 'Holly Carlill', '(no genres listed)', 2012, 78.76);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (243, 'Blue Denim', 'Harley Sleite', 'Drama', 2010, 297.6);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (244, 'In the Folds of the Flesh', 'Thedrick Seid', 'Drama|Horror|Thriller', 1990, 22.41);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (245, 'Babes in Toyland', 'Claudio Bowhay', 'Children|Fantasy|Musical', 1995, 62.91);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (246, 'Immortel (ad vitam) (Immortal)', 'Kara-lynn O''Concannon', 'Action|Adventure|Animation|Fantasy|Sci-Fi', 2019, 105.25);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (247, 'Diary of a Shinjuku Thief (Shinjuku dorobo nikki)', 'Yalonda Gummie', 'Comedy|Drama', 2000, 86.94);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (248, 'American Zombie', 'Garald Lebourn', 'Comedy|Horror', 1998, 432.64);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (249, 'Kill Bill: Vol. 2', 'Frasier Hazeldine', 'Action|Drama|Thriller', 2007, 39.11);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (250, 'Deadly Outlaw: Rekka (a.k.a. Violent Fire) (Jitsuroku Andô Noboru kyôdô-den: Rekka)', 'Anneliese Walles', 'Crime|Drama|Thriller', 2007, 70.41);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (251, 'World War Z', 'Mariette Rupp', 'Action|Drama|Horror|IMAX', 2020, 880.09);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (252, 'Boccaccio ''70', 'Sapphire Darbyshire', 'Comedy|Fantasy|Romance', 1990, 399.18);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (253, 'Old Fashioned Way, The', 'Minta Fincke', 'Comedy', 2024, 490.72);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (254, 'Starsuckers', 'Rowe Wallbrook', 'Documentary', 1999, 445.76);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (255, 'When We Were Kings', 'Janene Manning', 'Documentary', 2019, 502.07);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (256, 'Beach Blanket Bingo', 'Nicky Birchner', 'Comedy|Musical', 2006, 940.39);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (257, 'Next of Kin', 'Alphonso Dosdill', 'Action|Crime|Thriller', 2021, 618.22);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (258, 'Matchmaker, The', 'Devinne Zavattieri', 'Comedy|Romance', 2007, 666.37);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (259, 'Palestine Is Still the Issue', 'Wald Priditt', 'Documentary', 2012, 880.89);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (260, 'Nils Karlsson Pyssling', 'Fanny Shrimplin', 'Children', 2011, 886.12);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (261, 'Down to the Bone', 'Jeremy Stollberg', 'Drama', 2015, 507.86);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (262, 'Relationship Status: It''s Complicated', 'Merrily Yewman', 'Comedy|Romance', 2025, 367.85);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (263, 'Bête humaine, La', 'Gregorius Bullant', 'Drama', 2011, 217.52);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (264, 'Love Loves Coincidences', 'Kelwin Jahner', 'Drama|Romance', 2026, 899.14);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (265, 'Who''s Singin'' Over There? (a.k.a. Who Sings Over There) (Ko to tamo peva)', 'Margarete De Micoli', 'Comedy', 2020, 514.76);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (266, 'Storm Warriors, The (Fung wan II)', 'Timmie Devons', 'Action|Adventure|Fantasy', 2004, 961.04);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (267, 'Babel', 'Phelia Force', 'Drama|Thriller', 2026, 469.9);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (268, 'Descent: Part 2, The', 'Pepita Irwin', 'Adventure|Horror|Thriller', 2022, 357.52);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (269, 'Lord of the Rings: The Two Towers, The', 'Dwayne Lenormand', 'Adventure|Fantasy', 2011, 747.74);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (270, 'Broadway Bill', 'Iona Volke', 'Comedy|Drama', 2019, 593.35);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (271, 'Dr. Jekyll and Mr. Hyde', 'Ricard Digwood', 'Drama|Horror', 2000, 25.37);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (272, 'Heart of Me, The', 'Ellwood Maltby', 'Drama|Romance', 2009, 164.16);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (273, 'Curse of the Pink Panther', 'Analise Carayol', 'Comedy|Crime|Mystery', 1991, 551.24);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (274, 'God Is the Bigger Elvis', 'Rhonda Staden', 'Documentary', 2000, 501.81);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (275, 'Great Dictator, The', 'Melly Mitham', 'Comedy|Drama|War', 1997, 496.12);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (276, 'Eddie Murphy Delirious', 'Karla Sayce', 'Comedy|Documentary', 1994, 373.23);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (277, 'Woyzeck', 'Hatti Johnigan', 'Drama', 2019, 427.52);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (278, 'Big Fan', 'Yulma Iacopetti', 'Comedy|Crime|Drama', 1992, 685.54);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (279, 'Celtic Pride', 'Bobbie Bohman', 'Comedy', 2010, 344.19);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (280, 'Perfect', 'Kessia Charkham', 'Drama|Romance', 2012, 168.99);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (281, 'How I Won the War', 'Donni Skillicorn', 'Comedy|War', 1991, 458.11);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (282, 'Screwed', 'Bert Luety', 'Comedy', 2009, 980.95);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (283, 'Perfect Day, A (Un giorno perfetto)', 'Ursula Bau', 'Drama', 2018, 703.41);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (284, 'Deep, The', 'Alford Woolhouse', 'Adventure|Horror|Mystery|Thriller', 1992, 97.31);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (285, 'Secret Admirer', 'Byrann Rowberry', 'Comedy|Romance', 2007, 627.31);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (286, 'Kidnapped For Christ', 'Adoree Cockcroft', 'Documentary', 2015, 51.6);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (287, 'Summer Wishes, Winter Dreams', 'Filbert Cana', 'Drama', 2021, 661.75);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (288, 'Gator', 'Angelica Glede', 'Action|Drama', 2024, 637.55);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (289, 'Day Without a Mexican, A', 'Rosene Blasius', 'Comedy|Drama|Fantasy|Mystery', 2013, 93.45);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (290, 'Waste Land', 'Matthaeus Hepher', 'Documentary', 2004, 81.25);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (291, 'End of Days', 'Barth Grunwall', 'Action|Fantasy|Horror|Mystery|Thriller', 2000, 823.46);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (292, 'Rabbit', 'Murial MacAughtrie', 'Animation|Horror', 2005, 785.11);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (293, 'Wind, The', 'Genevieve Marron', 'Drama|Western', 2016, 241.83);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (294, 'Dracula', 'Ryley Seel', 'Horror|Romance', 2023, 579.98);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (295, 'Buffalo Girls', 'Geoffrey Drei', 'Action', 2008, 441.98);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (296, 'Moon-Spinners, The', 'Anne-marie Buckner', 'Children|Mystery', 1992, 824.59);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (297, 'Holokaustin värit', 'Northrup Mandifield', 'Documentary|War', 2010, 540.58);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (298, 'Harold & Kumar Escape from Guantanamo Bay', 'Charley Hargreves', 'Adventure|Comedy', 2016, 398.43);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (299, 'Nobody''s Children (I figli di nessuno)', 'Margarete Kaspar', 'Drama|Romance', 1994, 906.85);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (300, 'Quatsch und die Nasenbärbande', 'Cam Curry', 'Children', 1998, 968.88);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (301, 'Viva María!', 'Boothe Jewson', 'Adventure|Comedy|Western', 2014, 999.11);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (302, 'Fallout', 'Pip Satchel', 'Action|Sci-Fi', 2010, 68.86);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (303, 'Elevator', 'Emmeline Farloe', 'Comedy|Drama', 1994, 675.69);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (304, 'Occupants, The', 'Ambrosio Scandwright', 'Thriller', 2000, 131.19);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (305, 'ABCs of Death, The', 'Cecilio Yushankin', 'Horror', 1999, 440.87);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (306, 'Michael Collins', 'Klement Longmuir', 'Drama', 2020, 225.47);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (307, 'I''m Not Rappaport', 'Allx Yelden', 'Comedy', 2012, 256.25);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (308, 'Jesse James', 'Richardo Errichiello', 'Action|Crime|Drama|Romance|Western', 2003, 214.86);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (309, 'Caribe', 'Danyelle Tallboy', 'Drama|Mystery|Romance', 2000, 986.89);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (310, 'Jesus Camp', 'Wilbur Bendel', 'Documentary|Drama', 2003, 833.33);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (311, 'Heartbeat Detector (Question humaine, La)', 'Dagny Anthona', 'Drama|Thriller', 2019, 450.95);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (312, 'King of the Jungle', 'Nickola Teare', 'Drama|Thriller', 2002, 60.99);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (313, 'Officer and a Gentleman, An', 'Bess Plinck', 'Drama|Romance', 2010, 778.09);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (314, 'Mission: Impossible - Ghost Protocol', 'Clevie Rugieri', 'Action|Adventure|Thriller|IMAX', 2025, 72.87);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (315, 'Time Limit', 'Allin O''Mullally', 'Drama|Mystery|War', 2020, 921.91);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (316, 'Spring Forward', 'Dorise Jerzycowski', 'Drama', 2013, 430.64);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (317, 'Block Party (a.k.a. Dave Chappelle''s Block Party)', 'Cristi Iskov', 'Comedy|Documentary', 2002, 99.96);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (318, 'Why Worry?', 'Karalynn Catterell', 'Adventure|Comedy|Romance', 1999, 475.87);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (319, 'Return to Never Land', 'Ferrel Casale', 'Adventure|Animation|Children', 2020, 642.11);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (320, 'Slaughter of the Innocents', 'Herrick Roswarne', 'Crime|Horror|Mystery|Thriller', 1997, 485.26);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (321, 'Christine', 'Frayda Gawler', 'Horror', 2022, 496.19);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (322, 'Fiston', 'Raffarty Lethibridge', 'Comedy', 1997, 289.15);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (323, 'Iceberg, L''', 'Wendy Sainte Paul', 'Comedy', 2012, 104.74);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (324, 'Southern Comfort', 'Stephenie Dearing', 'Drama|Thriller|War', 1999, 313.33);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (325, 'No Mercy', 'Rupert Matuska', 'Action|Crime|Thriller', 1999, 186.91);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (326, 'Indestructible Man', 'Devan Grenfell', 'Crime|Horror|Sci-Fi', 1995, 670.35);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (327, 'Lauderdale (a.k.a. Spring Break USA) (a.k.a. Spring Fever USA)', 'Obed Roels', 'Comedy', 2008, 573.99);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (328, 'Big Day, The (We Met on the Vineyard)', 'Granger McVane', 'Comedy', 1995, 685.51);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (329, 'Falcon and the Snowman, The', 'Catherine Simone', 'Drama|Thriller', 1992, 743.59);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (330, 'Electric Boogaloo: The Wild, Untold Story of Cannon Films', 'Gene Elbourn', 'Comedy|Documentary', 2008, 599.79);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (331, 'Cube 2: Hypercube', 'Corny Scriviner', 'Horror|Mystery|Sci-Fi', 2007, 269.55);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (332, 'Solid Gold Cadillac, The', 'Kamila Childes', 'Comedy', 2013, 780.3);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (333, 'Suspect, The', 'Dyanna Omand', 'Drama|Thriller', 2016, 48.26);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (334, 'Easy Money (Snabba Cash)', 'Damien Slemming', 'Action|Thriller', 1991, 141.17);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (335, 'Van, The', 'Culver MacKeller', 'Comedy|Drama', 1996, 74.47);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (336, 'Fear Over the City', 'Hendrick Morriss', 'Action|Crime|Drama', 1997, 162.77);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (337, 'Favor, The', 'Leda Perrett', 'Comedy|Romance', 1995, 23.36);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (338, 'Zatoichi and the Chest of Gold (Zatôichi senryô-kubi) (Zatôichi 6)', 'Philipa Bende', 'Action|Drama', 2026, 963.75);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (339, 'Parallel Sons', 'Sonnnie Isselee', 'Drama|Romance', 2004, 238.53);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (340, 'Last Flight of Noah''s Ark, The', 'Trisha Caroll', 'Adventure|Children|Comedy', 1995, 185.34);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (341, 'So Much Water', 'Kaja Lamort', 'Comedy|Drama', 1998, 687.88);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (342, 'Creepshow 2', 'Alicia McFaul', 'Horror', 2012, 243.87);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (343, 'Hustle', 'Pauly Osborn', 'Crime|Drama|Mystery|Thriller', 1991, 810.04);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (344, 'Hotel Pacific (Zaklete rewiry)', 'Louis Cragoe', 'Drama', 2012, 699.49);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (345, 'Star, The', 'Almeta Buckhurst', 'Drama', 2025, 464.49);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (346, 'North by Northwest', 'Igor Potts', 'Action|Adventure|Mystery|Romance|Thriller', 1993, 195.43);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (347, 'Brother, Can You Spare a Dime?', 'Charlotte Pickworth', 'Documentary', 1999, 871.02);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (348, 'Play Motel', 'Garland Prendergast', 'Crime|Horror|Thriller', 2014, 792.06);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (349, 'Rally On! (Ralliraita)', 'Lona Twycross', 'Comedy', 2009, 819.54);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (350, 'Adrenalin: Fear the Rush', 'Boony Horsted', 'Action|Sci-Fi', 2001, 56.04);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (351, 'End of Days', 'Farley Brickstock', 'Action|Fantasy|Horror|Mystery|Thriller', 1993, 868.18);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (352, 'Sniper: Reloaded ', 'Anabel Tonner', 'Action|Drama|Thriller|War', 2008, 86.06);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (353, 'Bengazi', 'Marven Dondon', 'Adventure|Crime|Drama', 2026, 302.24);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (354, 'Herbie Rides Again', 'Dale Chetwynd', 'Adventure|Children|Comedy', 1990, 381.73);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (355, 'Castle on the Hudson', 'Goober Litton', 'Crime|Drama', 1994, 603.44);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (356, 'Days of Thunder', 'Florian Kinge', 'Action|Drama|Romance', 1998, 814.86);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (357, 'Low Down, The', 'Dario Smithend', 'Drama', 2009, 965.23);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (358, 'Constantine''s Sword', 'Lizabeth Phillpotts', 'Documentary', 1998, 292.78);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (359, 'Trance', 'Robinette Bellelli', 'Horror', 2016, 212.62);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (360, 'Snake and Mongoose', 'Anderson Davis', 'Drama', 2007, 514.91);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (361, 'Howard the Duck', 'Peder Gostick', 'Adventure|Comedy|Sci-Fi', 2023, 332.0);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (362, 'Deadly Tower, The', 'Jacques Skentelbury', 'Action|Drama|Thriller', 2026, 493.0);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (363, 'Monsters vs Aliens: Mutant Pumpkins from Outer Space', 'Nicolais Moggie', 'Animation|Comedy|Sci-Fi', 1991, 799.2);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (364, 'Paper Heart', 'Prudi Bennallck', 'Comedy|Documentary|Drama|Romance', 1998, 514.86);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (365, 'Green Ray, The (Rayon vert, Le)', 'Arline Dulake', 'Drama|Romance', 1993, 761.94);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (366, 'I Thank a Fool', 'Marabel Ramshaw', 'Drama', 1995, 551.33);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (367, 'Edukators, The (Die Fetten Jahre sind vorbei)', 'Laurent Mager', 'Comedy|Crime|Drama|Romance', 2021, 564.95);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (368, 'Sidewalls (Medianeras)', 'Andeee Hissett', 'Drama', 2020, 285.22);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (369, 'Day of the Dead 2: Contagium', 'Samantha Wittman', 'Horror|Sci-Fi', 2019, 932.08);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (370, 'Sixth of the World, A (Shestaya chast mira)', 'Margaux Pieter', 'Documentary', 2015, 743.29);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (371, 'Mother''s Day', 'Miranda Mead', 'Comedy|Horror', 2005, 47.63);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (372, 'One Body Too Many', 'Meade Woollcott', 'Comedy|Horror|Mystery', 2007, 291.45);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (373, 'Saltmen of Tibet, The (Salzmänner von Tibet, Die)', 'Lucas McFadzean', 'Documentary', 2019, 936.63);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (374, 'Surrogates', 'Tallulah Reuven', 'Action|Sci-Fi|Thriller', 2009, 713.42);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (375, 'Far from Home', 'Ardelis Oguz', 'Thriller', 2010, 923.36);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (376, 'One Life', 'Elise MacCurtain', 'Documentary', 1998, 588.5);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (377, 'Steel Toes', 'Renell Shimon', 'Crime|Drama', 2003, 383.01);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (378, 'Slumming', 'Hal Pennells', 'Comedy|Drama', 2008, 924.97);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (379, 'WNUF Halloween Special', 'Katine O''Gavin', 'Comedy|Horror', 1990, 659.09);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (380, 'Shadows (Cienie)', 'Katrinka Spiniello', 'Drama', 1996, 109.89);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (381, 'Lady for a Day', 'Lia Leyzell', 'Comedy', 1994, 689.76);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (382, 'Rapa Nui', 'Baily Overell', 'Action|Adventure|Drama|Romance', 2020, 11.47);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (383, 'Sound of Insects, The', 'Darsey Trustey', 'Adventure|Documentary|Drama|Mystery|Thriller', 2017, 989.55);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (384, 'Animals are Beautiful People', 'Layne Brownsell', 'Comedy|Documentary', 2012, 878.35);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (385, 'Claymation Christmas Celebration, A', 'Alden Splaven', 'Animation|Children|Comedy|Musical', 1997, 830.39);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (386, 'Yankee Doodle Dandy', 'Selinda Pinnere', 'Drama|Musical', 2013, 665.74);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (387, 'Criminals', 'Davin Cargill', 'Documentary', 2014, 765.39);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (388, 'Grand Masti', 'Ondrea Addicote', 'Comedy|Drama|Romance', 2007, 650.9);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (389, 'There''s Always Tomorrow', 'Micky James', 'Drama', 2024, 551.17);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (390, 'H6: Diario de un asesino', 'Veda Bulman', 'Horror|Thriller', 2006, 9.6);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (391, 'Perfect Fake, A', 'Eddie Darmody', 'Documentary', 1990, 214.03);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (392, 'Hitman Hart: Wrestling with Shadows', 'Rhoda Brodest', 'Documentary', 2019, 786.2);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (393, 'Rise of Catherine the Great, The', 'Euell Pearce', 'Drama', 2002, 899.27);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (394, 'Mission, The (Cheung fo)', 'Juliana Philipp', 'Crime|Drama|Mystery', 2026, 825.63);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (395, 'Mad Money', 'Lydon McAllester', 'Comedy|Crime|Thriller', 1997, 923.48);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (396, 'When the Bough Breaks', 'Carce Fibbens', 'Drama|Thriller', 2009, 287.2);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (397, 'Eddie Izzard: Dress to Kill', 'Bird Foulgham', 'Comedy', 2004, 495.01);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (398, 'Unstoppable', 'Quentin McWard', 'Action|Adventure|Comedy|Drama|Thriller', 2001, 50.48);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (399, 'How to Make Money Selling Drugs', 'Harlene Costigan', 'Documentary', 2002, 709.71);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (400, '200 Motels', 'Felicity Stockhill', 'Comedy|Musical', 2004, 94.05);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (401, 'Cat Returns, The (Neko no ongaeshi)', 'Rosabel Aizkovitch', 'Adventure|Animation|Children|Fantasy', 2003, 157.47);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (402, 'Big Pun: The Legacy', 'Zahara Rainbird', 'Documentary', 2026, 150.39);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (403, 'Crane World (Mundo grúa)', 'Job Annetts', 'Comedy|Drama', 1994, 131.95);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (404, 'Synchromy', 'Georgie Hotson', 'Animation', 2014, 538.32);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (405, 'Drag Me to Hell', 'Gwynne Dibsdale', 'Comedy|Horror', 2003, 806.76);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (406, 'Married to It', 'Arnie Fulun', 'Comedy|Drama', 2024, 874.4);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (407, 'The 39 Steps', 'Port Sewill', 'Crime|Mystery|Thriller', 2007, 283.58);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (408, 'Smooth Talk', 'Andreana Mellonby', 'Drama|Romance', 2004, 76.43);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (409, 'World According to Sesame Street, The', 'Birch Trengove', 'Documentary|War', 1990, 786.41);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (410, 'The Trial of Lee Harvey Oswald', 'Darn Ferron', 'Drama', 2017, 272.47);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (411, 'Invincible', 'Kassie Schoular', 'Drama', 2019, 368.5);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (412, 'Gods and Monsters', 'Ranna Rontsch', 'Drama', 2018, 893.93);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (413, 'How Hitler Lost the War', 'Lynette Kelwaybamber', 'Documentary', 2017, 119.79);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (414, 'Go for Sisters', 'Carolan Bellringer', 'Crime|Drama', 2004, 744.68);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (415, 'Come Have Coffee with Us', 'Shandra Sambals', 'Comedy', 2000, 78.96);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (416, 'Blue Blood', 'Eleanor Ticehurst', 'Documentary', 2000, 370.0);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (417, 'Attack of the Mushroom People (Matango)', 'Kristan Whardley', 'Fantasy|Horror|Sci-Fi|Thriller', 2014, 936.32);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (418, 'So Big!', 'Licha Troy', 'Drama', 2013, 767.76);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (419, 'Charleston', 'Kalina Pawelek', 'Comedy', 1991, 486.75);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (420, 'For Neda', 'Willie Getten', 'Documentary', 2006, 554.02);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (421, 'Woman''s Face, A', 'Emery Maltman', 'Drama|Thriller', 1994, 625.65);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (422, 'Fat, Sick & Nearly Dead', 'Diane-marie Wagenen', 'Documentary', 2004, 792.37);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (423, 'Second Civil War, The', 'Judd Jepp', 'Comedy|Drama', 1990, 487.88);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (424, 'Lady Vengeance (Sympathy for Lady Vengeance) (Chinjeolhan geumjassi)', 'Trish Livingston', 'Crime|Drama|Mystery|Thriller', 2009, 313.0);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (425, 'Man with the Screaming Brain', 'Antonetta Sheppard', 'Adventure|Comedy|Sci-Fi', 1993, 848.35);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (426, 'Once Upon a Time in Shanghai', 'Carey Kausche', 'Crime', 2025, 68.76);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (427, 'Pelicanman (Pelikaanimies)', 'Fanny Angus', 'Adventure|Children|Fantasy', 1991, 620.32);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (428, 'Bakery Girl of Monceau, The (La boulangère de Monceau)', 'Ty Diggar', 'Romance', 2023, 962.57);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (429, 'Pokémon the Movie: White - Victini and Zekrom', 'Lisa Behagg', 'Animation', 1999, 529.52);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (430, 'Plaisir, Le', 'Emelina Reaney', 'Comedy|Drama', 2025, 382.26);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (431, 'Big Easy Express', 'Heindrick Frankcomb', 'Documentary|Musical', 2002, 645.05);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (432, 'Hamlet', 'Mellisent Aslen', 'Crime|Drama|Romance|Thriller', 2003, 525.14);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (433, 'Mansion of Madness, The', 'Lorraine Langtry', 'Horror', 2010, 794.85);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (434, 'Skylark', 'Fanny Eat', 'Children|Drama', 2021, 496.57);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (435, 'Uptown Saturday Night', 'Felicity Wondraschek', 'Comedy', 2007, 946.07);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (436, 'Missing in Action 2: The Beginning', 'Brittan Kubica', 'Action|War', 2019, 578.53);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (437, 'Flower in Hell (Jiokhwa)', 'Angelina Barden', 'Crime|Drama', 2005, 738.17);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (438, 'American Vagabond', 'Eugenia Forri', 'Documentary', 2001, 668.1);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (439, 'Little Odessa', 'Quincy Millery', 'Crime|Drama', 2002, 590.92);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (440, 'Ms. 45 (a.k.a. Angel of Vengeance)', 'Eduino Joss', 'Crime|Drama', 2001, 169.21);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (441, 'Day the Earth Stood Still, The', 'Jayne Bewley', 'Drama|Sci-Fi|Thriller|IMAX', 1991, 685.84);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (442, 'The Legend of Sarila', 'Lyndsay Reidie', 'Adventure|Animation|Children', 2002, 730.03);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (443, 'Temptress Moon (Feng Yue)', 'Boigie Coltman', 'Romance', 2013, 950.87);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (444, 'Ledge, The', 'Vickie Yitzhakov', 'Drama|Thriller', 2018, 42.52);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (445, 'Frenchmen 2', 'Binnie McPharlain', 'Comedy|Romance', 2025, 623.82);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (446, 'Case Against 8, The', 'Selina Mechi', 'Documentary', 2026, 157.43);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (447, '14 Hours (Fourteen Hours)', 'Alexandra Falkinder', 'Drama|Film-Noir|Thriller', 1993, 847.05);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (448, 'Twin Peaks: Fire Walk with Me', 'Malinda Torri', 'Crime|Drama|Mystery|Thriller', 2004, 678.33);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (449, 'Money (L''argent)', 'Karol Redsell', 'Crime|Drama', 2001, 605.64);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (450, 'Nightwing', 'Dominica Itscowicz', 'Horror', 2023, 176.82);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (451, 'RiP: A Remix Manifesto', 'Harmony Marchbank', 'Documentary', 2011, 547.02);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (452, 'Dead Silence', 'Bank Gillise', 'Action|Drama|Thriller', 1992, 686.36);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (453, 'Ultimate Avengers', 'Hallie Ruppel', 'Action|Animation|Children|Sci-Fi', 2020, 622.97);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (454, 'When a Stranger Calls', 'Miller Pittson', 'Horror|Thriller', 2020, 857.1);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (455, 'Mother''s Courage: Talking Back to Autism, A', 'Nickolaus Hulke', 'Documentary', 1998, 280.56);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (456, 'Opening Night', 'Candy Keneleyside', 'Drama', 2018, 105.1);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (457, 'Crow, The: Wicked Prayer', 'Kenton McLardie', 'Action|Adventure|Fantasy|Thriller', 2011, 880.95);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (458, 'Hell Drivers', 'Noak Trout', 'Drama', 2013, 410.06);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (459, 'This Ain''t California', 'Neda Kibbe', 'Documentary', 2012, 296.45);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (460, 'Batch ''81', 'Gayla MacAnelley', 'Drama', 2013, 868.14);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (461, 'City of Fear', 'Derward Crannis', 'Crime|Thriller', 2016, 35.53);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (462, 'Tibet: Cry of the Snow Lion', 'Virgilio Vyel', 'Documentary', 1996, 459.44);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (463, 'Waterboys', 'Beniamino Gemson', 'Comedy', 2024, 88.39);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (464, 'Very Happy Alexander (Alexandre le bienheureux)', 'Ophelia Brundill', 'Comedy|Romance', 2011, 469.82);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (465, 'Natural Selection', 'Ker Wadman', 'Comedy|Drama', 1991, 52.47);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (466, 'Crime Wave', 'Suellen Dewan', 'Crime|Drama|Film-Noir', 2015, 135.62);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (467, 'Women of the Night (Yoru no onnatachi)', 'Nananne Gresty', 'Drama', 2021, 666.61);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (468, 'The Punisher: Dirty Laundry', 'Darb Wheaton', 'Action|Crime|Drama', 2004, 260.18);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (469, '13B', 'Robinetta Grieves', 'Horror|Mystery|Thriller', 2018, 178.93);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (470, 'How to Be', 'Elisha Tripett', 'Comedy|Drama', 2023, 116.62);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (471, 'Six Ways to Sunday', 'Addie Pulham', 'Comedy', 2006, 466.0);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (472, 'Dorian Gray', 'Agneta Bicksteth', 'Drama|Horror|Sci-Fi', 2009, 431.47);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (473, 'Confidentially Yours (Vivement dimanche!)', 'Ally Strippling', 'Comedy|Crime|Mystery|Thriller', 2002, 5.08);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (474, 'Days of Grace (Días de gracia) ', 'Rebekkah Matschek', 'Thriller', 1995, 94.9);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (475, 'McLintock!', 'Laurens Heading', 'Comedy|Western', 2026, 406.94);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (476, 'Hotel', 'Terrye Silby', 'Drama', 2010, 72.59);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (477, 'Devil Doll', 'Dominik Carbry', 'Horror', 1994, 379.36);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (478, 'At the Earth''s Core', 'Maximilien Littlefair', 'Adventure|Sci-Fi', 2017, 109.32);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (479, 'Godzilla vs. The Sea Monster (Gojira-Ebira-Mosura: Nankai no daiketto)', 'Sampson Confait', 'Action|Adventure|Fantasy|Sci-Fi', 2022, 946.36);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (480, 'Densha otoko (Train Man)', 'Korry Harsnipe', 'Comedy|Romance', 2001, 128.83);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (481, 'Voyage to the Prehistoric Planet', 'Valentia Barry', 'Adventure|Sci-Fi', 2007, 844.31);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (482, 'Let''s Not Keep in Touch!', 'Darcey Billsberry', 'Comedy', 2011, 765.22);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (483, 'Julien Donkey-Boy', 'Marie Bortolazzi', 'Drama', 2002, 287.06);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (484, '51 Birch Street', 'West Caghy', 'Documentary', 2015, 643.67);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (485, 'Man in the Iron Mask, The', 'Sayre Pettwood', 'Adventure', 2010, 648.29);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (486, 'From Time to Time', 'Marilyn Muehler', 'Adventure|Drama|Fantasy', 2005, 447.26);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (487, 'Fast, Cheap & Out of Control', 'Bink Mathevet', 'Documentary', 2001, 660.25);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (488, 'Being Elmo: A Puppeteer''s Journey', 'Ellswerth Sebert', 'Documentary', 2002, 407.81);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (489, 'Nights of Cabiria (Notti di Cabiria, Le)', 'Reuben Oleshunin', 'Drama', 2024, 400.21);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (490, 'Xala', 'Jacquelynn Hearl', 'Comedy', 2017, 182.87);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (491, 'Marion Bridge', 'Claudianus MacGinley', 'Drama', 2002, 725.04);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (492, 'Double Dynamite', 'Ossie Jiggen', 'Comedy|Musical', 1990, 772.17);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (493, 'Entertaining Angels: The Dorothy Day Story', 'Marilee Hallbord', 'Drama', 2010, 150.61);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (494, 'Black Robe', 'Sterne Jaslem', 'Adventure|Drama', 2020, 533.94);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (495, 'Zen', 'Edi Ebrall', 'Drama', 2020, 843.17);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (496, 'The Vengeance of Fu Manchu', 'Peadar Sebert', 'Action|Crime|Drama|Horror', 1995, 55.94);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (497, 'Grand Day Out with Wallace and Gromit, A', 'Kristan Vel', 'Adventure|Animation|Children|Comedy|Sci-Fi', 2024, 197.6);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (498, 'Hollidaysburg', 'Griff Lomas', 'Comedy', 2006, 183.69);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (499, 'Vanity Fair', 'Larine Josephoff', 'Drama|Romance', 2008, 304.31);
insert into Libri (id, titolo, autore, genere, anno_pubblicazione, prezzo) values (500, 'Dragonfly', 'Cyndia Alchin', 'Drama', 1996, 328.5);